version: '3.9'

services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: AlemEsv
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: root
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
  web:
    build:
      context: .
      dockerfile: dockerfile
    container_name: fastapi-app
    ports:
      - "80:80"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/code
